/**
 * NexusIAM Connector Registry
 * Defines 35+ connector types — their config schema, native attribute schema,
 * provisioning capabilities, and authentication methods.
 *
 * Just like SailPoint IdentityIQ connector catalog.
 */

const CONNECTORS = {

  // ─── DIRECTORY SERVICES ────────────────────────────────────────────────────

  active_directory: {
    displayName: 'Active Directory',
    category: 'Directory',
    icon: 'windows',
    description: 'Microsoft Active Directory via LDAP/S',
    authType: 'ldap_bind',
    protocol: 'ldap',
    defaultPort: 389,
    securePorts: [636],
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'password_set', 'group_management'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'host', label: 'Domain Controller Host', type: 'text', required: true, placeholder: 'dc.company.com' },
      { key: 'port', label: 'Port', type: 'number', default: 389 },
      { key: 'ssl', label: 'Use SSL/TLS (LDAPS)', type: 'boolean', default: false },
      { key: 'bind_dn', label: 'Bind DN', type: 'text', required: true, placeholder: 'CN=SvcAccount,OU=ServiceAccounts,DC=company,DC=com' },
      { key: 'bind_password', label: 'Bind Password', type: 'password', required: true },
      { key: 'base_dn', label: 'Base DN', type: 'text', required: true, placeholder: 'DC=company,DC=com' },
      { key: 'user_search_base', label: 'User Search Base', type: 'text', placeholder: 'OU=Users,DC=company,DC=com' },
      { key: 'user_filter', label: 'User Filter', type: 'text', default: '(objectClass=user)', placeholder: '(&(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))' },
      { key: 'group_search_base', label: 'Group Search Base', type: 'text', placeholder: 'OU=Groups,DC=company,DC=com' },
      { key: 'group_filter', label: 'Group Filter', type: 'text', default: '(objectClass=group)' },
      { key: 'page_size', label: 'Page Size', type: 'number', default: 1000 },
      { key: 'referral', label: 'Referral Handling', type: 'select', options: ['ignore', 'follow'], default: 'ignore' },
    ],
    nativeSchema: [
      { name: 'sAMAccountName', type: 'string', description: 'Logon name (pre-Windows 2000)', isUid: true },
      { name: 'userPrincipalName', type: 'string', description: 'UPN - format: user@domain.com' },
      { name: 'distinguishedName', type: 'string', description: 'Full DN path' },
      { name: 'cn', type: 'string', description: 'Common Name' },
      { name: 'givenName', type: 'string', description: 'First Name' },
      { name: 'sn', type: 'string', description: 'Last Name (Surname)' },
      { name: 'displayName', type: 'string', description: 'Display Name' },
      { name: 'mail', type: 'string', description: 'Email Address' },
      { name: 'telephoneNumber', type: 'string', description: 'Phone Number' },
      { name: 'mobile', type: 'string', description: 'Mobile Number' },
      { name: 'department', type: 'string', description: 'Department' },
      { name: 'title', type: 'string', description: 'Job Title' },
      { name: 'company', type: 'string', description: 'Company Name' },
      { name: 'manager', type: 'string', description: 'Manager DN' },
      { name: 'memberOf', type: 'multi_string', description: 'Group Memberships (DN list)' },
      { name: 'userAccountControl', type: 'number', description: 'Account control flags (512=enabled, 514=disabled)' },
      { name: 'accountExpires', type: 'datetime', description: 'Account Expiration Date' },
      { name: 'pwdLastSet', type: 'datetime', description: 'Password Last Set' },
      { name: 'lastLogon', type: 'datetime', description: 'Last Logon Timestamp' },
      { name: 'employeeID', type: 'string', description: 'Employee ID' },
      { name: 'employeeNumber', type: 'string', description: 'Employee Number' },
      { name: 'streetAddress', type: 'string', description: 'Street Address' },
      { name: 'l', type: 'string', description: 'City (locality)' },
      { name: 'st', type: 'string', description: 'State/Province' },
      { name: 'co', type: 'string', description: 'Country' },
      { name: 'postalCode', type: 'string', description: 'Postal Code' },
      { name: 'description', type: 'string', description: 'Description' },
      { name: 'objectGUID', type: 'binary', description: 'Unique AD Object GUID', readOnly: true },
      { name: 'objectSid', type: 'binary', description: 'Security Identifier', readOnly: true },
      { name: 'whenCreated', type: 'datetime', description: 'Account Created', readOnly: true },
      { name: 'whenChanged', type: 'datetime', description: 'Account Last Modified', readOnly: true },
    ],
  },

  ldap: {
    displayName: 'Generic LDAP',
    category: 'Directory',
    icon: 'directory',
    description: 'Generic LDAP v3 directory (OpenLDAP, Oracle DS, etc.)',
    authType: 'ldap_bind',
    protocol: 'ldap',
    defaultPort: 389,
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'host', label: 'LDAP Host', type: 'text', required: true },
      { key: 'port', label: 'Port', type: 'number', default: 389 },
      { key: 'ssl', label: 'Use SSL', type: 'boolean', default: false },
      { key: 'bind_dn', label: 'Bind DN', type: 'text', required: true },
      { key: 'bind_password', label: 'Bind Password', type: 'password', required: true },
      { key: 'base_dn', label: 'Base DN', type: 'text', required: true },
      { key: 'user_object_class', label: 'User Object Class', type: 'text', default: 'inetOrgPerson' },
      { key: 'uid_attribute', label: 'UID Attribute', type: 'text', default: 'uid' },
    ],
    nativeSchema: [
      { name: 'uid', type: 'string', description: 'User ID', isUid: true },
      { name: 'cn', type: 'string', description: 'Common Name' },
      { name: 'sn', type: 'string', description: 'Surname' },
      { name: 'givenName', type: 'string', description: 'Given Name' },
      { name: 'mail', type: 'string', description: 'Email' },
      { name: 'userPassword', type: 'password', description: 'Password Hash' },
      { name: 'telephoneNumber', type: 'string', description: 'Phone' },
      { name: 'o', type: 'string', description: 'Organization' },
      { name: 'ou', type: 'string', description: 'Organizational Unit' },
      { name: 'description', type: 'string', description: 'Description' },
      { name: 'memberOf', type: 'multi_string', description: 'Group Memberships' },
    ],
  },

  // ─── CLOUD IAM PLATFORMS ───────────────────────────────────────────────────

  okta: {
    displayName: 'Okta',
    category: 'Cloud IAM',
    icon: 'okta',
    description: 'Okta Identity Platform - Users, Groups, Apps via REST API',
    authType: 'api_token',
    protocol: 'rest',
    baseUrlTemplate: 'https://{domain}.okta.com',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'password_set', 'group_management', 'app_assignment'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'domain', label: 'Okta Domain', type: 'text', required: true, placeholder: 'yourcompany' },
      { key: 'api_token', label: 'API Token', type: 'password', required: true, placeholder: 'SSWS ...' },
      { key: 'rate_limit_per_min', label: 'Rate Limit (req/min)', type: 'number', default: 600 },
      { key: 'import_groups', label: 'Import Groups', type: 'boolean', default: true },
      { key: 'import_apps', label: 'Import App Assignments', type: 'boolean', default: true },
    ],
    nativeSchema: [
      { name: 'login', type: 'string', description: 'Okta Login (username)', isUid: true },
      { name: 'email', type: 'string', description: 'Primary Email' },
      { name: 'firstName', type: 'string', description: 'First Name' },
      { name: 'lastName', type: 'string', description: 'Last Name' },
      { name: 'displayName', type: 'string', description: 'Display Name' },
      { name: 'nickName', type: 'string', description: 'Nick Name' },
      { name: 'mobilePhone', type: 'string', description: 'Mobile Phone' },
      { name: 'primaryPhone', type: 'string', description: 'Primary Phone' },
      { name: 'streetAddress', type: 'string', description: 'Street Address' },
      { name: 'city', type: 'string', description: 'City' },
      { name: 'state', type: 'string', description: 'State' },
      { name: 'zipCode', type: 'string', description: 'Zip Code' },
      { name: 'countryCode', type: 'string', description: 'Country Code (ISO 3166-1)' },
      { name: 'postalAddress', type: 'string', description: 'Postal Address' },
      { name: 'preferredLanguage', type: 'string', description: 'Preferred Language' },
      { name: 'locale', type: 'string', description: 'Locale' },
      { name: 'timezone', type: 'string', description: 'Timezone' },
      { name: 'title', type: 'string', description: 'Title' },
      { name: 'department', type: 'string', description: 'Department' },
      { name: 'organization', type: 'string', description: 'Organization' },
      { name: 'division', type: 'string', description: 'Division' },
      { name: 'costCenter', type: 'string', description: 'Cost Center' },
      { name: 'employeeNumber', type: 'string', description: 'Employee Number' },
      { name: 'manager', type: 'string', description: 'Manager Login' },
      { name: 'managerId', type: 'string', description: 'Manager ID' },
      { name: 'status', type: 'string', description: 'Account Status (ACTIVE/DEPROVISIONED)', readOnly: true },
      { name: 'id', type: 'string', description: 'Okta User ID', readOnly: true },
      { name: 'created', type: 'datetime', description: 'Created Date', readOnly: true },
      { name: 'lastLogin', type: 'datetime', description: 'Last Login', readOnly: true },
      { name: 'groups', type: 'multi_string', description: 'Group Names' },
    ],
    schemaDiscoveryEndpoint: '/api/v1/meta/schemas/user/default',
  },

  azure_ad: {
    displayName: 'Azure Active Directory / Entra ID',
    category: 'Cloud IAM',
    icon: 'microsoft',
    description: 'Microsoft Azure AD / Entra ID via Microsoft Graph API',
    authType: 'oauth2_client_credentials',
    protocol: 'rest',
    baseUrl: 'https://graph.microsoft.com/v1.0',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'password_set', 'group_management', 'license_management'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'tenant_id', label: 'Tenant ID', type: 'text', required: true, placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' },
      { key: 'client_id', label: 'Application (Client) ID', type: 'text', required: true },
      { key: 'client_secret', label: 'Client Secret', type: 'password', required: true },
      { key: 'import_groups', label: 'Import Groups', type: 'boolean', default: true },
      { key: 'import_licenses', label: 'Import License Assignments', type: 'boolean', default: false },
      { key: 'user_filter', label: 'User Filter (OData)', type: 'text', placeholder: "accountEnabled eq true and userType eq 'Member'" },
    ],
    nativeSchema: [
      { name: 'userPrincipalName', type: 'string', description: 'User Principal Name (UPN)', isUid: true },
      { name: 'id', type: 'string', description: 'Azure AD Object ID', readOnly: true },
      { name: 'displayName', type: 'string', description: 'Display Name' },
      { name: 'givenName', type: 'string', description: 'First Name' },
      { name: 'surname', type: 'string', description: 'Last Name' },
      { name: 'mail', type: 'string', description: 'Email Address' },
      { name: 'mailNickname', type: 'string', description: 'Mail Nickname / Alias' },
      { name: 'mobilePhone', type: 'string', description: 'Mobile Phone' },
      { name: 'businessPhones', type: 'multi_string', description: 'Business Phone Numbers' },
      { name: 'jobTitle', type: 'string', description: 'Job Title' },
      { name: 'department', type: 'string', description: 'Department' },
      { name: 'companyName', type: 'string', description: 'Company Name' },
      { name: 'employeeId', type: 'string', description: 'Employee ID' },
      { name: 'employeeType', type: 'string', description: 'Employee Type' },
      { name: 'officeLocation', type: 'string', description: 'Office Location' },
      { name: 'city', type: 'string', description: 'City' },
      { name: 'state', type: 'string', description: 'State' },
      { name: 'country', type: 'string', description: 'Country' },
      { name: 'postalCode', type: 'string', description: 'Postal Code' },
      { name: 'streetAddress', type: 'string', description: 'Street Address' },
      { name: 'preferredLanguage', type: 'string', description: 'Preferred Language' },
      { name: 'usageLocation', type: 'string', description: 'Usage Location (ISO 3166-1 alpha-2)' },
      { name: 'accountEnabled', type: 'boolean', description: 'Account Enabled' },
      { name: 'passwordProfile', type: 'object', description: 'Password Profile (for reset)' },
      { name: 'memberOf', type: 'multi_string', description: 'Group Memberships', readOnly: true },
      { name: 'createdDateTime', type: 'datetime', description: 'Created Date', readOnly: true },
      { name: 'lastSignInDateTime', type: 'datetime', description: 'Last Sign-In', readOnly: true },
      { name: 'onPremisesSamAccountName', type: 'string', description: 'On-Prem SAM Account Name' },
      { name: 'onPremisesDistinguishedName', type: 'string', description: 'On-Prem DN' },
      { name: 'proxyAddresses', type: 'multi_string', description: 'Proxy Email Addresses' },
    ],
    schemaDiscoveryEndpoint: '/users/$metadata',
  },

  google_workspace: {
    displayName: 'Google Workspace',
    category: 'Cloud IAM',
    icon: 'google',
    description: 'Google Workspace Directory API (formerly G Suite)',
    authType: 'oauth2_service_account',
    protocol: 'rest',
    baseUrl: 'https://admin.googleapis.com/admin/directory/v1',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'password_set', 'group_management'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'customer_id', label: 'Customer ID', type: 'text', required: true, placeholder: 'C0xxxxxxx' },
      { key: 'domain', label: 'Primary Domain', type: 'text', required: true, placeholder: 'company.com' },
      { key: 'service_account_key', label: 'Service Account Key (JSON)', type: 'textarea', required: true },
      { key: 'admin_email', label: 'Admin Email (for impersonation)', type: 'text', required: true },
      { key: 'import_groups', label: 'Import Groups/OUs', type: 'boolean', default: true },
    ],
    nativeSchema: [
      { name: 'primaryEmail', type: 'string', description: 'Primary Email Address', isUid: true },
      { name: 'id', type: 'string', description: 'Google Directory User ID', readOnly: true },
      { name: 'name.givenName', type: 'string', description: 'First Name' },
      { name: 'name.familyName', type: 'string', description: 'Last Name' },
      { name: 'name.fullName', type: 'string', description: 'Full Name' },
      { name: 'suspended', type: 'boolean', description: 'Account Suspended' },
      { name: 'orgUnitPath', type: 'string', description: 'Org Unit Path' },
      { name: 'recoveryEmail', type: 'string', description: 'Recovery Email' },
      { name: 'recoveryPhone', type: 'string', description: 'Recovery Phone' },
      { name: 'phones', type: 'multi_object', description: 'Phone Numbers (type+value)' },
      { name: 'addresses', type: 'multi_object', description: 'Addresses (type+formatted)' },
      { name: 'organizations', type: 'multi_object', description: 'Organizations (title, dept, etc.)' },
      { name: 'relations', type: 'multi_object', description: 'Relations (manager, etc.)' },
      { name: 'aliases', type: 'multi_string', description: 'Email Aliases' },
      { name: 'lastLoginTime', type: 'datetime', description: 'Last Login', readOnly: true },
      { name: 'creationTime', type: 'datetime', description: 'Creation Time', readOnly: true },
      { name: 'isAdmin', type: 'boolean', description: 'Is Super Admin' },
      { name: 'customerId', type: 'string', description: 'Customer ID', readOnly: true },
      { name: 'thumbnailPhotoUrl', type: 'string', description: 'Profile Photo URL' },
      { name: 'includeInGlobalAddressList', type: 'boolean', description: 'Include in GAL' },
      { name: 'customSchemas', type: 'object', description: 'Custom Schema Fields' },
    ],
  },

  // ─── DATABASE CONNECTORS ───────────────────────────────────────────────────

  jdbc_postgresql: {
    displayName: 'JDBC - PostgreSQL',
    category: 'Database',
    icon: 'database',
    description: 'PostgreSQL database via JDBC-style queries',
    authType: 'username_password',
    protocol: 'jdbc',
    defaultPort: 5432,
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'host', label: 'Database Host', type: 'text', required: true },
      { key: 'port', label: 'Port', type: 'number', default: 5432 },
      { key: 'database', label: 'Database Name', type: 'text', required: true },
      { key: 'username', label: 'Username', type: 'text', required: true },
      { key: 'password', label: 'Password', type: 'password', required: true },
      { key: 'ssl', label: 'Use SSL', type: 'boolean', default: false },
      { key: 'user_table', label: 'User Table Name', type: 'text', required: true, placeholder: 'users' },
      { key: 'uid_column', label: 'UID Column', type: 'text', required: true, placeholder: 'username' },
      { key: 'query_all_users', label: 'Fetch All Users SQL', type: 'textarea', placeholder: 'SELECT * FROM users WHERE active = true' },
      { key: 'query_get_user', label: 'Fetch Single User SQL', type: 'textarea', placeholder: 'SELECT * FROM users WHERE username = ?' },
      { key: 'query_create_user', label: 'Create User SQL', type: 'textarea' },
      { key: 'query_update_user', label: 'Update User SQL', type: 'textarea' },
      { key: 'query_delete_user', label: 'Delete/Disable User SQL', type: 'textarea' },
    ],
    nativeSchema: [], // Discovered dynamically from table columns
    dynamicSchema: true,
  },

  jdbc_mysql: {
    displayName: 'JDBC - MySQL / MariaDB',
    category: 'Database',
    icon: 'database',
    description: 'MySQL or MariaDB via direct connection',
    authType: 'username_password',
    protocol: 'jdbc',
    defaultPort: 3306,
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'host', label: 'Database Host', type: 'text', required: true, placeholder: 'host.docker.internal' },
      { key: 'port', label: 'Port', type: 'number', default: 3306 },
      { key: 'database', label: 'Database Name', type: 'text', required: true },
      { key: 'username', label: 'Username', type: 'text', required: true },
      { key: 'password', label: 'Password', type: 'password', required: true },
      { key: 'user_table', label: 'User Table Name', type: 'text', required: true },
      { key: 'uid_column', label: 'UID Column', type: 'text', required: true },
      { key: 'fetch_all_users_sql', label: 'Fetch All Users SQL', type: 'textarea' },
      { key: 'create_user_sql', label: 'Create User SQL', type: 'textarea' },
      { key: 'update_user_sql', label: 'Update User SQL', type: 'textarea' },
      { key: 'delete_user_sql', label: 'Delete / Disable User SQL', type: 'textarea' },
      { key: 'display_attribute', label: 'Display Attribute', type: 'text', placeholder: 'display_name' },
      { key: 'account_name_attribute', label: 'Account Name Attribute', type: 'text', placeholder: 'display_name / email' },
      { key: 'status_attribute', label: 'Status Attribute', type: 'text', placeholder: 'status / is_active' },
      { key: 'identity_attribute', label: 'Identity Attribute', type: 'text', placeholder: 'email / employee_id' },
      { key: 'correlation_attribute', label: 'Correlation Attribute', type: 'text', placeholder: 'email / employee_id / id' },
    ],
    nativeSchema: [],
    dynamicSchema: true,
  },

  jdbc_mssql: {
    displayName: 'JDBC - Microsoft SQL Server',
    category: 'Database',
    icon: 'database',
    description: 'Microsoft SQL Server via direct connection',
    authType: 'username_password',
    protocol: 'jdbc',
    defaultPort: 1433,
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'host', label: 'Database Host', type: 'text', required: true, placeholder: 'host.docker.internal' },
      { key: 'port', label: 'Port', type: 'number', default: 1433 },
      { key: 'database', label: 'Database Name', type: 'text', required: true },
      { key: 'username', label: 'Username', type: 'text', required: true },
      { key: 'password', label: 'Password', type: 'password', required: true },
      { key: 'domain', label: 'Windows Domain (for NTLM)', type: 'text' },
      { key: 'instance', label: 'SQL Instance Name', type: 'text' },
      { key: 'user_table', label: 'User Table Name', type: 'text', required: true },
      { key: 'uid_column', label: 'UID Column', type: 'text', required: true },
      { key: 'fetch_all_users_sql', label: 'Fetch All Users SQL', type: 'textarea' },
      { key: 'create_user_sql', label: 'Create User SQL', type: 'textarea' },
      { key: 'update_user_sql', label: 'Update User SQL', type: 'textarea' },
      { key: 'delete_user_sql', label: 'Delete / Disable User SQL', type: 'textarea' },
      { key: 'display_attribute', label: 'Display Attribute', type: 'text' },
      { key: 'account_name_attribute', label: 'Account Name Attribute', type: 'text' },
      { key: 'status_attribute', label: 'Status Attribute', type: 'text' },
      { key: 'identity_attribute', label: 'Identity Attribute', type: 'text' },
      { key: 'correlation_attribute', label: 'Correlation Attribute', type: 'text' },
    ],
    nativeSchema: [],
    dynamicSchema: true,
  },

  jdbc_oracle: {
    displayName: 'JDBC - Oracle Database',
    category: 'Database',
    icon: 'database',
    description: 'Oracle Database via direct connection',
    authType: 'username_password',
    protocol: 'jdbc',
    defaultPort: 1521,
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'host', label: 'Host', type: 'text', required: true },
      { key: 'port', label: 'Port', type: 'number', default: 1521 },
      { key: 'service_name', label: 'Service Name / SID', type: 'text', required: true },
      { key: 'username', label: 'Username', type: 'text', required: true },
      { key: 'password', label: 'Password', type: 'password', required: true },
      { key: 'user_table', label: 'User Table', type: 'text', required: true },
      { key: 'uid_column', label: 'UID Column', type: 'text', required: true },
    ],
    nativeSchema: [],
    dynamicSchema: true,
  },

  // ─── SCIM 2.0 COMPLIANT ────────────────────────────────────────────────────

  scim2: {
    displayName: 'SCIM 2.0 (Generic)',
    category: 'Standard Protocol',
    icon: 'scim',
    description: 'Any application with a SCIM 2.0 endpoint',
    authType: 'bearer_token',
    protocol: 'scim',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'group_management'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'base_url', label: 'SCIM Base URL', type: 'text', required: true, placeholder: 'https://app.example.com/scim/v2' },
      { key: 'auth_type', label: 'Auth Type', type: 'select', options: ['bearer_token', 'basic_auth', 'oauth2'], default: 'bearer_token' },
      { key: 'bearer_token', label: 'Bearer Token', type: 'password', showIf: { key: 'auth_type', value: 'bearer_token', default: 'bearer_token' } },
      { key: 'basic_username', label: 'Basic Auth Username', type: 'text', showIf: { key: 'auth_type', value: 'basic_auth' } },
      { key: 'basic_password', label: 'Basic Auth Password', type: 'password', showIf: { key: 'auth_type', value: 'basic_auth' } },
      { key: 'oauth2_token_url', label: 'OAuth2 Token URL', type: 'text', placeholder: 'https://auth.example.com/oauth/token', showIf: { key: 'auth_type', value: 'oauth2' } },
      { key: 'oauth2_client_id', label: 'OAuth2 Client ID', type: 'text', showIf: { key: 'auth_type', value: 'oauth2' } },
      { key: 'oauth2_client_secret', label: 'OAuth2 Client Secret', type: 'password', showIf: { key: 'auth_type', value: 'oauth2' } },
      { key: 'page_size', label: 'Page Size', type: 'number', default: 100 },
      { key: 'import_groups', label: 'Import Groups', type: 'boolean', default: true },
    ],
    nativeSchema: [
      { name: 'userName', type: 'string', description: 'SCIM userName', isUid: true },
      { name: 'id', type: 'string', description: 'SCIM Resource ID', readOnly: true },
      { name: 'externalId', type: 'string', description: 'External ID (your system ID)' },
      { name: 'name.givenName', type: 'string', description: 'First Name' },
      { name: 'name.familyName', type: 'string', description: 'Last Name' },
      { name: 'name.formatted', type: 'string', description: 'Full Name' },
      { name: 'emails[primary].value', type: 'string', description: 'Primary Email' },
      { name: 'phoneNumbers[work].value', type: 'string', description: 'Work Phone' },
      { name: 'phoneNumbers[mobile].value', type: 'string', description: 'Mobile Phone' },
      { name: 'addresses[work].streetAddress', type: 'string', description: 'Street Address' },
      { name: 'addresses[work].locality', type: 'string', description: 'City' },
      { name: 'addresses[work].region', type: 'string', description: 'State/Region' },
      { name: 'addresses[work].country', type: 'string', description: 'Country' },
      { name: 'title', type: 'string', description: 'Job Title' },
      { name: 'department', type: 'string', description: 'Department' },
      { name: 'active', type: 'boolean', description: 'Account Active' },
      { name: 'groups', type: 'multi_string', description: 'Group Memberships', readOnly: true },
    ],
    schemaDiscoveryEndpoint: '/ServiceProviderConfig',
  },

  // ─── ENTERPRISE SaaS ──────────────────────────────────────────────────────

  salesforce: {
    displayName: 'Salesforce',
    category: 'Enterprise SaaS',
    icon: 'salesforce',
    description: 'Salesforce CRM via REST API and SOAP',
    authType: 'oauth2_password',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'profile_assignment'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'instance_url', label: 'Salesforce Instance URL', type: 'text', required: true, placeholder: 'https://yourorg.salesforce.com' },
      { key: 'client_id', label: 'Connected App Client ID', type: 'text', required: true },
      { key: 'client_secret', label: 'Connected App Client Secret', type: 'password', required: true },
      { key: 'username', label: 'Salesforce Username', type: 'text', required: true },
      { key: 'password', label: 'Password + Security Token', type: 'password', required: true },
      { key: 'api_version', label: 'API Version', type: 'text', default: 'v59.0' },
      { key: 'sandbox', label: 'Sandbox Environment', type: 'boolean', default: false },
    ],
    nativeSchema: [
      { name: 'Username', type: 'string', description: 'Salesforce Username (email)', isUid: true },
      { name: 'Id', type: 'string', description: 'Salesforce User ID', readOnly: true },
      { name: 'FirstName', type: 'string', description: 'First Name' },
      { name: 'LastName', type: 'string', description: 'Last Name' },
      { name: 'Email', type: 'string', description: 'Email Address' },
      { name: 'FederationIdentifier', type: 'string', description: 'SSO Federation ID' },
      { name: 'Title', type: 'string', description: 'Title' },
      { name: 'Department', type: 'string', description: 'Department' },
      { name: 'CompanyName', type: 'string', description: 'Company Name' },
      { name: 'Phone', type: 'string', description: 'Phone' },
      { name: 'MobilePhone', type: 'string', description: 'Mobile Phone' },
      { name: 'EmployeeNumber', type: 'string', description: 'Employee Number' },
      { name: 'ManagerId', type: 'string', description: 'Manager User ID' },
      { name: 'ProfileId', type: 'string', description: 'Profile ID' },
      { name: 'UserRoleId', type: 'string', description: 'Role ID' },
      { name: 'IsActive', type: 'boolean', description: 'Account Active' },
      { name: 'TimeZoneSidKey', type: 'string', description: 'Timezone' },
      { name: 'LocaleSidKey', type: 'string', description: 'Locale' },
      { name: 'LanguageLocaleKey', type: 'string', description: 'Language' },
      { name: 'CreatedDate', type: 'datetime', description: 'Created Date', readOnly: true },
      { name: 'LastLoginDate', type: 'datetime', description: 'Last Login Date', readOnly: true },
    ],
  },

  workday: {
    displayName: 'Workday',
    category: 'HR Systems',
    icon: 'workday',
    description: 'Workday HCM — authoritative HR source of truth',
    authType: 'basic_auth',
    protocol: 'soap_rest',
    capabilities: ['read', 'create', 'update'],
    provisioningDirection: ['pull', 'push'],
    configSchema: [
      { key: 'tenant', label: 'Workday Tenant', type: 'text', required: true, placeholder: 'mycompany_preview' },
      { key: 'username', label: 'ISU Username', type: 'text', required: true, placeholder: 'ISU_NexusIAM@mycompany' },
      { key: 'password', label: 'ISU Password', type: 'password', required: true },
      { key: 'version', label: 'API Version', type: 'text', default: 'v41.0' },
      { key: 'worker_type', label: 'Worker Type Filter', type: 'select', options: ['All', 'Employee', 'Contingent_Worker'], default: 'All' },
      { key: 'include_terminated', label: 'Include Terminated Workers', type: 'boolean', default: false },
    ],
    nativeSchema: [
      { name: 'Employee_ID', type: 'string', description: 'Workday Employee ID', isUid: true },
      { name: 'Worker_ID', type: 'string', description: 'Workday Worker ID' },
      { name: 'User_Name', type: 'string', description: 'Workday Username' },
      { name: 'First_Name', type: 'string', description: 'First Name' },
      { name: 'Last_Name', type: 'string', description: 'Last Name' },
      { name: 'Preferred_Name', type: 'string', description: 'Preferred Name' },
      { name: 'Email_Address', type: 'string', description: 'Work Email' },
      { name: 'Phone_Number', type: 'string', description: 'Work Phone' },
      { name: 'Mobile_Number', type: 'string', description: 'Mobile Number' },
      { name: 'Job_Title', type: 'string', description: 'Job Title' },
      { name: 'Department', type: 'string', description: 'Department' },
      { name: 'Cost_Center', type: 'string', description: 'Cost Center' },
      { name: 'Manager_Employee_ID', type: 'string', description: 'Manager Employee ID' },
      { name: 'Location', type: 'string', description: 'Work Location' },
      { name: 'Country', type: 'string', description: 'Country' },
      { name: 'Hire_Date', type: 'date', description: 'Hire Date' },
      { name: 'Termination_Date', type: 'date', description: 'Termination Date' },
      { name: 'Worker_Type', type: 'string', description: 'Worker Type' },
      { name: 'Employment_Status', type: 'string', description: 'Employment Status' },
      { name: 'Business_Unit', type: 'string', description: 'Business Unit' },
      { name: 'Company', type: 'string', description: 'Legal Company' },
    ],
  },

  servicenow: {
    displayName: 'ServiceNow',
    category: 'ITSM',
    icon: 'servicenow',
    description: 'ServiceNow ITSM - User table, roles, groups via REST API',
    authType: 'basic_auth',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'instance_url', label: 'Instance URL', type: 'text', required: true, placeholder: 'https://yourcompany.service-now.com' },
      { key: 'username', label: 'Username', type: 'text', required: true },
      { key: 'password', label: 'Password', type: 'password', required: true },
      { key: 'user_table', label: 'User Table', type: 'text', default: 'sys_user' },
      { key: 'query_filter', label: 'User Query Filter', type: 'text', placeholder: 'active=true' },
    ],
    nativeSchema: [
      { name: 'user_name', type: 'string', description: 'Username', isUid: true },
      { name: 'sys_id', type: 'string', description: 'System ID', readOnly: true },
      { name: 'first_name', type: 'string', description: 'First Name' },
      { name: 'last_name', type: 'string', description: 'Last Name' },
      { name: 'email', type: 'string', description: 'Email' },
      { name: 'title', type: 'string', description: 'Title' },
      { name: 'department', type: 'string', description: 'Department (reference)' },
      { name: 'company', type: 'string', description: 'Company (reference)' },
      { name: 'manager', type: 'string', description: 'Manager (reference)' },
      { name: 'phone', type: 'string', description: 'Phone' },
      { name: 'mobile_phone', type: 'string', description: 'Mobile Phone' },
      { name: 'active', type: 'boolean', description: 'Active' },
      { name: 'locked_out', type: 'boolean', description: 'Locked Out' },
      { name: 'last_login_time', type: 'datetime', description: 'Last Login', readOnly: true },
      { name: 'roles', type: 'multi_string', description: 'Role Names' },
    ],
    dynamicSchema: true,
  },

  sap_hcm: {
    displayName: 'SAP HCM / SuccessFactors',
    category: 'HR Systems',
    icon: 'sap',
    description: 'SAP HCM or SuccessFactors as authoritative HR source',
    authType: 'basic_auth',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update'],
    provisioningDirection: ['pull', 'push'],
    configSchema: [
      { key: 'base_url', label: 'SuccessFactors API URL', type: 'text', required: true, placeholder: 'https://api.successfactors.com' },
      { key: 'company_id', label: 'Company ID', type: 'text', required: true },
      { key: 'username', label: 'API Username', type: 'text', required: true, placeholder: 'admin@COMPANY_ID' },
      { key: 'password', label: 'API Password', type: 'password', required: true },
      { key: 'entity', label: 'Entity Type', type: 'select', options: ['User', 'PerPerson', 'EmpEmployment', 'EmpJob'], default: 'User' },
    ],
    nativeSchema: [
      { name: 'userId', type: 'string', description: 'User ID', isUid: true },
      { name: 'username', type: 'string', description: 'Username' },
      { name: 'firstName', type: 'string', description: 'First Name' },
      { name: 'lastName', type: 'string', description: 'Last Name' },
      { name: 'email', type: 'string', description: 'Email' },
      { name: 'division', type: 'string', description: 'Division' },
      { name: 'department', type: 'string', description: 'Department' },
      { name: 'title', type: 'string', description: 'Job Title' },
      { name: 'hireDate', type: 'date', description: 'Hire Date' },
      { name: 'manager', type: 'string', description: 'Manager User ID' },
      { name: 'location', type: 'string', description: 'Location' },
      { name: 'status', type: 'string', description: 'Employment Status' },
    ],
  },

  github: {
    displayName: 'GitHub Enterprise / Cloud',
    category: 'Developer Tools',
    icon: 'github',
    description: 'GitHub organization users and teams via REST API',
    authType: 'personal_access_token',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'group_management'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'org', label: 'Organization Name', type: 'text', required: true },
      { key: 'token', label: 'Personal Access Token', type: 'password', required: true },
      { key: 'enterprise_url', label: 'Enterprise URL (if on-prem)', type: 'text', placeholder: 'https://github.mycompany.com' },
      { key: 'import_teams', label: 'Import Teams', type: 'boolean', default: true },
    ],
    nativeSchema: [
      { name: 'login', type: 'string', description: 'GitHub Login', isUid: true },
      { name: 'id', type: 'number', description: 'GitHub User ID', readOnly: true },
      { name: 'name', type: 'string', description: 'Display Name' },
      { name: 'email', type: 'string', description: 'Public Email' },
      { name: 'company', type: 'string', description: 'Company' },
      { name: 'role', type: 'string', description: 'Org Role (member/admin)' },
      { name: 'teams', type: 'multi_string', description: 'Team Slugs' },
    ],
  },

  jira: {
    displayName: 'Jira / Confluence (Atlassian)',
    category: 'Productivity',
    icon: 'atlassian',
    description: 'Atlassian Jira and Confluence user provisioning via REST API',
    authType: 'api_token',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'group_management'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'base_url', label: 'Atlassian Cloud URL', type: 'text', required: true, placeholder: 'https://yourcompany.atlassian.net' },
      { key: 'email', label: 'Admin Email', type: 'text', required: true },
      { key: 'api_token', label: 'API Token', type: 'password', required: true },
      { key: 'import_groups', label: 'Import Groups', type: 'boolean', default: true },
    ],
    nativeSchema: [
      { name: 'emailAddress', type: 'string', description: 'Email Address', isUid: true },
      { name: 'accountId', type: 'string', description: 'Atlassian Account ID', readOnly: true },
      { name: 'displayName', type: 'string', description: 'Display Name' },
      { name: 'active', type: 'boolean', description: 'Account Active' },
      { name: 'groups', type: 'multi_string', description: 'Groups' },
    ],
  },

  slack: {
    displayName: 'Slack',
    category: 'Collaboration',
    icon: 'slack',
    description: 'Slack workspace user management via SCIM 2.0 / API',
    authType: 'bearer_token',
    protocol: 'scim',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'group_management'],
    provisioningDirection: ['push', 'pull'],
    configSchema: [
      { key: 'workspace_token', label: 'SCIM OAuth Token', type: 'password', required: true },
      { key: 'workspace_url', label: 'Workspace URL', type: 'text', placeholder: 'https://yourcompany.slack.com' },
    ],
    nativeSchema: [
      { name: 'userName', type: 'string', description: 'Slack Username / Email', isUid: true },
      { name: 'id', type: 'string', description: 'Slack User ID', readOnly: true },
      { name: 'name.givenName', type: 'string', description: 'First Name' },
      { name: 'name.familyName', type: 'string', description: 'Last Name' },
      { name: 'displayName', type: 'string', description: 'Display Name' },
      { name: 'title', type: 'string', description: 'Title' },
      { name: 'department', type: 'string', description: 'Department' },
      { name: 'active', type: 'boolean', description: 'Active' },
      { name: 'emails[primary].value', type: 'string', description: 'Primary Email' },
    ],
  },

  aws_iam: {
    displayName: 'AWS IAM / SSO',
    category: 'Cloud Platform',
    icon: 'aws',
    description: 'AWS IAM users, roles, and groups via AWS SDK / Identity Center',
    authType: 'aws_credentials',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'group_management', 'role_management'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'access_key_id', label: 'AWS Access Key ID', type: 'text', required: true },
      { key: 'secret_access_key', label: 'AWS Secret Access Key', type: 'password', required: true },
      { key: 'region', label: 'AWS Region', type: 'text', default: 'us-east-1' },
      { key: 'identity_store_id', label: 'Identity Center Store ID', type: 'text', placeholder: 'd-xxxxxxxxxx' },
      { key: 'use_iam_identity_center', label: 'Use IAM Identity Center (SSO)', type: 'boolean', default: false },
    ],
    nativeSchema: [
      { name: 'UserName', type: 'string', description: 'IAM Username', isUid: true },
      { name: 'UserId', type: 'string', description: 'IAM User ID', readOnly: true },
      { name: 'Arn', type: 'string', description: 'ARN', readOnly: true },
      { name: 'Email', type: 'string', description: 'Email (from tags)' },
      { name: 'Groups', type: 'multi_string', description: 'Group Names' },
      { name: 'Tags', type: 'object', description: 'Resource Tags' },
      { name: 'CreateDate', type: 'datetime', description: 'Created Date', readOnly: true },
    ],
  },

  box: {
    displayName: 'Box',
    category: 'Cloud Storage',
    icon: 'box',
    description: 'Box.com enterprise content management user provisioning',
    authType: 'oauth2_jwt',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'group_management'],
    provisioningDirection: ['push', 'pull'],
    configSchema: [
      { key: 'client_id', label: 'Client ID', type: 'text', required: true },
      { key: 'client_secret', label: 'Client Secret', type: 'password', required: true },
      { key: 'enterprise_id', label: 'Enterprise ID', type: 'text', required: true },
      { key: 'jwt_private_key', label: 'JWT Private Key', type: 'textarea' },
      { key: 'jwt_key_id', label: 'JWT Key ID', type: 'text' },
    ],
    nativeSchema: [
      { name: 'login', type: 'string', description: 'Email / Login', isUid: true },
      { name: 'id', type: 'string', description: 'Box User ID', readOnly: true },
      { name: 'name', type: 'string', description: 'Display Name' },
      { name: 'status', type: 'string', description: 'Status (active/inactive)' },
      { name: 'role', type: 'string', description: 'Enterprise Role' },
      { name: 'job_title', type: 'string', description: 'Job Title' },
      { name: 'phone', type: 'string', description: 'Phone' },
    ],
  },

  zoom: {
    displayName: 'Zoom',
    category: 'Collaboration',
    icon: 'zoom',
    description: 'Zoom video platform user provisioning via REST API',
    authType: 'oauth2_server_to_server',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'group_management'],
    provisioningDirection: ['push', 'pull'],
    configSchema: [
      { key: 'account_id', label: 'Account ID', type: 'text', required: true },
      { key: 'client_id', label: 'Client ID', type: 'text', required: true },
      { key: 'client_secret', label: 'Client Secret', type: 'password', required: true },
    ],
    nativeSchema: [
      { name: 'email', type: 'string', description: 'Email Address', isUid: true },
      { name: 'id', type: 'string', description: 'Zoom User ID', readOnly: true },
      { name: 'first_name', type: 'string', description: 'First Name' },
      { name: 'last_name', type: 'string', description: 'Last Name' },
      { name: 'display_name', type: 'string', description: 'Display Name' },
      { name: 'type', type: 'number', description: 'User Type (1=Basic, 2=Licensed, 3=Enterprise)' },
      { name: 'status', type: 'string', description: 'Status (active/inactive)' },
      { name: 'dept', type: 'string', description: 'Department' },
      { name: 'job_title', type: 'string', description: 'Job Title' },
      { name: 'phone_numbers', type: 'multi_string', description: 'Phone Numbers' },
      { name: 'group_ids', type: 'multi_string', description: 'Group IDs' },
    ],
  },

  dropbox: {
    displayName: 'Dropbox Business',
    category: 'Cloud Storage',
    icon: 'dropbox',
    description: 'Dropbox Business user provisioning via API',
    authType: 'bearer_token',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable'],
    provisioningDirection: ['push', 'pull'],
    configSchema: [
      { key: 'api_token', label: 'Team API Token', type: 'password', required: true },
    ],
    nativeSchema: [
      { name: 'email', type: 'string', description: 'Email', isUid: true },
      { name: 'account_id', type: 'string', description: 'Dropbox Account ID', readOnly: true },
      { name: 'name.display_name', type: 'string', description: 'Display Name' },
      { name: 'name.given_name', type: 'string', description: 'First Name' },
      { name: 'name.surname', type: 'string', description: 'Last Name' },
      { name: 'status', type: 'string', description: 'Status' },
      { name: 'role', type: 'string', description: 'Role' },
    ],
  },

  hubspot: {
    displayName: 'HubSpot',
    category: 'CRM',
    icon: 'hubspot',
    description: 'HubSpot CRM user and owner management via REST API',
    authType: 'api_token',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable'],
    provisioningDirection: ['push', 'pull'],
    configSchema: [
      { key: 'api_key', label: 'Private App Token', type: 'password', required: true },
    ],
    nativeSchema: [
      { name: 'email', type: 'string', description: 'Email', isUid: true },
      { name: 'id', type: 'string', description: 'User ID', readOnly: true },
      { name: 'firstName', type: 'string', description: 'First Name' },
      { name: 'lastName', type: 'string', description: 'Last Name' },
      { name: 'roleIds', type: 'multi_string', description: 'Role IDs' },
    ],
  },

  zendesk: {
    displayName: 'Zendesk',
    category: 'Customer Support',
    icon: 'zendesk',
    description: 'Zendesk Support user provisioning via REST API',
    authType: 'api_token',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'group_management'],
    provisioningDirection: ['push', 'pull'],
    configSchema: [
      { key: 'subdomain', label: 'Zendesk Subdomain', type: 'text', required: true, placeholder: 'yourcompany' },
      { key: 'email', label: 'Admin Email', type: 'text', required: true },
      { key: 'api_token', label: 'API Token', type: 'password', required: true },
    ],
    nativeSchema: [
      { name: 'email', type: 'string', description: 'Email', isUid: true },
      { name: 'id', type: 'number', description: 'User ID', readOnly: true },
      { name: 'name', type: 'string', description: 'Display Name' },
      { name: 'role', type: 'string', description: 'Role (admin/agent/end-user)' },
      { name: 'active', type: 'boolean', description: 'Active' },
      { name: 'organization_id', type: 'number', description: 'Organization ID' },
      { name: 'phone', type: 'string', description: 'Phone' },
    ],
  },

  pingidentity: {
    displayName: 'Ping Identity / PingOne',
    category: 'Cloud IAM',
    icon: 'ping',
    description: 'Ping Identity PingOne directory and SSO',
    authType: 'oauth2_client_credentials',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'group_management'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'environment_id', label: 'Environment ID', type: 'text', required: true },
      { key: 'client_id', label: 'Client ID', type: 'text', required: true },
      { key: 'client_secret', label: 'Client Secret', type: 'password', required: true },
      { key: 'region', label: 'Region', type: 'select', options: ['NorthAmerica', 'Europe', 'AsiaPacific'], default: 'NorthAmerica' },
    ],
    nativeSchema: [
      { name: 'username', type: 'string', description: 'Username', isUid: true },
      { name: 'id', type: 'string', description: 'PingOne User ID', readOnly: true },
      { name: 'name.given', type: 'string', description: 'First Name' },
      { name: 'name.family', type: 'string', description: 'Last Name' },
      { name: 'email', type: 'string', description: 'Email' },
      { name: 'title', type: 'string', description: 'Title' },
      { name: 'enabled', type: 'boolean', description: 'Enabled' },
      { name: 'mfaEnabled', type: 'boolean', description: 'MFA Enabled' },
      { name: 'population', type: 'object', description: 'Population' },
    ],
  },

  cyberark: {
    displayName: 'CyberArk PAM',
    category: 'Privileged Access',
    icon: 'cyberark',
    description: 'CyberArk Privileged Access Management - vault accounts',
    authType: 'cyberark_auth',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete'],
    provisioningDirection: ['push', 'pull'],
    configSchema: [
      { key: 'pvwa_url', label: 'PVWA URL', type: 'text', required: true, placeholder: 'https://pvwa.company.com' },
      { key: 'username', label: 'CyberArk Username', type: 'text', required: true },
      { key: 'password', label: 'Password', type: 'password', required: true },
      { key: 'auth_type', label: 'Auth Method', type: 'select', options: ['CyberArk', 'LDAP', 'SAML', 'Radius'], default: 'CyberArk' },
      { key: 'safe_filter', label: 'Safe Name Filter', type: 'text', placeholder: 'Shared' },
    ],
    nativeSchema: [
      { name: 'UserName', type: 'string', description: 'Account Username', isUid: true },
      { name: 'Address', type: 'string', description: 'Target Server Address' },
      { name: 'SafeName', type: 'string', description: 'Safe Name' },
      { name: 'PlatformId', type: 'string', description: 'Platform ID' },
      { name: 'AccountId', type: 'string', description: 'CyberArk Account ID', readOnly: true },
    ],
  },

  beyondtrust: {
    displayName: 'BeyondTrust / BeyondInsight',
    category: 'Privileged Access',
    icon: 'beyondtrust',
    description: 'BeyondTrust PAM - privileged account provisioning',
    authType: 'api_key',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable'],
    provisioningDirection: ['push', 'pull'],
    configSchema: [
      { key: 'host', label: 'BeyondInsight Host', type: 'text', required: true },
      { key: 'api_key', label: 'API Key', type: 'password', required: true },
      { key: 'username', label: 'Username', type: 'text', required: true },
      { key: 'password', label: 'Password', type: 'password', required: true },
    ],
    nativeSchema: [
      { name: 'UserName', type: 'string', description: 'Username', isUid: true },
      { name: 'UserId', type: 'number', description: 'User ID', readOnly: true },
      { name: 'EmailAddress', type: 'string', description: 'Email' },
      { name: 'FirstName', type: 'string', description: 'First Name' },
      { name: 'LastName', type: 'string', description: 'Last Name' },
      { name: 'IsActive', type: 'boolean', description: 'Active' },
    ],
  },

  saml_idp: {
    displayName: 'SAML 2.0 (Generic IdP)',
    category: 'Standard Protocol',
    icon: 'saml',
    description: 'Any SAML 2.0 Identity Provider integration',
    authType: 'saml2',
    protocol: 'saml',
    capabilities: ['sso', 'slo', 'attribute_mapping'],
    provisioningDirection: ['pull'],
    configSchema: [
      { key: 'idp_metadata_url', label: 'IdP Metadata URL', type: 'text', placeholder: 'https://idp.company.com/saml/metadata' },
      { key: 'idp_metadata_xml', label: 'IdP Metadata XML', type: 'textarea' },
      { key: 'sp_entity_id', label: 'SP Entity ID', type: 'text', placeholder: 'https://nexusiam.company.com' },
      { key: 'sp_acs_url', label: 'SP ACS URL', type: 'text', placeholder: 'https://nexusiam.company.com/sso/saml/acs' },
      { key: 'name_id_format', label: 'NameID Format', type: 'select', options: ['email', 'persistent', 'transient', 'unspecified'], default: 'email' },
      { key: 'sign_requests', label: 'Sign Auth Requests', type: 'boolean', default: true },
      { key: 'want_assertions_signed', label: 'Require Signed Assertions', type: 'boolean', default: true },
    ],
    nativeSchema: [
      { name: 'NameID', type: 'string', description: 'SAML NameID', isUid: true },
      { name: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress', type: 'string', description: 'Email Claim' },
      { name: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname', type: 'string', description: 'First Name Claim' },
      { name: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname', type: 'string', description: 'Last Name Claim' },
      { name: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/groups', type: 'multi_string', description: 'Groups Claim' },
    ],
  },

  oidc_provider: {
    displayName: 'OpenID Connect (Generic IdP)',
    category: 'Standard Protocol',
    icon: 'oidc',
    description: 'Any OIDC 1.0 compliant Identity Provider',
    authType: 'oidc',
    protocol: 'oidc',
    capabilities: ['sso', 'attribute_mapping'],
    provisioningDirection: ['pull'],
    configSchema: [
      { key: 'discovery_url', label: 'Discovery URL (.well-known)', type: 'text', placeholder: 'https://idp.company.com/.well-known/openid-configuration' },
      { key: 'client_id', label: 'Client ID', type: 'text', required: true },
      { key: 'client_secret', label: 'Client Secret', type: 'password', required: true },
      { key: 'scopes', label: 'Scopes', type: 'text', default: 'openid email profile groups' },
      { key: 'redirect_uri', label: 'Redirect URI', type: 'text' },
    ],
    nativeSchema: [
      { name: 'sub', type: 'string', description: 'Subject Identifier', isUid: true },
      { name: 'email', type: 'string', description: 'Email' },
      { name: 'email_verified', type: 'boolean', description: 'Email Verified' },
      { name: 'given_name', type: 'string', description: 'First Name' },
      { name: 'family_name', type: 'string', description: 'Last Name' },
      { name: 'name', type: 'string', description: 'Full Name' },
      { name: 'groups', type: 'multi_string', description: 'Groups' },
      { name: 'preferred_username', type: 'string', description: 'Username' },
    ],
  },

  rest_generic: {
    displayName: 'REST API (Generic)',
    category: 'Custom',
    icon: 'api',
    description: 'Any REST API application — fully configurable endpoints',
    authType: 'configurable',
    protocol: 'rest',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'base_url', label: 'Base URL', type: 'text', required: true },
      { key: 'auth_type', label: 'Auth Type', type: 'select', options: ['none', 'basic', 'bearer_token', 'api_key', 'oauth2'], default: 'bearer_token' },
      { key: 'auth_token', label: 'Auth Token / Key', type: 'password' },
      { key: 'auth_header', label: 'Auth Header Name', type: 'text', default: 'Authorization' },
      { key: 'list_users_endpoint', label: 'List Users Endpoint', type: 'text', placeholder: 'GET /users' },
      { key: 'get_user_endpoint', label: 'Get User Endpoint', type: 'text', placeholder: 'GET /users/{id}' },
      { key: 'create_user_endpoint', label: 'Create User Endpoint', type: 'text', placeholder: 'POST /users' },
      { key: 'update_user_endpoint', label: 'Update User Endpoint', type: 'text', placeholder: 'PUT /users/{id}' },
      { key: 'delete_user_endpoint', label: 'Delete User Endpoint', type: 'text', placeholder: 'DELETE /users/{id}' },
      { key: 'users_json_path', label: 'Users Array JSON Path', type: 'text', placeholder: '$.data.users' },
      { key: 'uid_field', label: 'UID Field Name', type: 'text', required: true, placeholder: 'id' },
      { key: 'extra_headers', label: 'Extra Headers (JSON)', type: 'textarea', placeholder: '{"X-Tenant":"myorg"}' },
    ],
    nativeSchema: [],
    dynamicSchema: true,
  },

  csv_flat_file: {
    displayName: 'CSV / Flat File',
    category: 'File-based',
    icon: 'file',
    description: 'CSV file import/export — HR feed, bulk load, legacy systems',
    authType: 'file_path',
    protocol: 'file',
    capabilities: ['read', 'create', 'update'],
    provisioningDirection: ['pull', 'push'],
    configSchema: [
      { key: 'file_path', label: 'File Path (server)', type: 'text', placeholder: '/data/hr-feed.csv' },
      { key: 'delimiter', label: 'Delimiter', type: 'select', options: [',', ';', '|', '\t'], default: ',' },
      { key: 'has_header', label: 'Has Header Row', type: 'boolean', default: true },
      { key: 'encoding', label: 'File Encoding', type: 'select', options: ['UTF-8', 'UTF-16', 'ISO-8859-1', 'Windows-1252'], default: 'UTF-8' },
      { key: 'uid_column', label: 'UID Column Name/Index', type: 'text', required: true },
      { key: 'date_format', label: 'Date Format', type: 'text', default: 'YYYY-MM-DD' },
      { key: 'sftp_host', label: 'SFTP Host (if remote)', type: 'text' },
      { key: 'sftp_port', label: 'SFTP Port', type: 'number', default: 22 },
      { key: 'sftp_username', label: 'SFTP Username', type: 'text' },
      { key: 'sftp_password', label: 'SFTP Password', type: 'password' },
    ],
    nativeSchema: [],
    dynamicSchema: true, // Columns discovered from CSV header
  },

  custom_jar: {
    displayName: 'Custom Connector (JAR)',
    category: 'Custom',
    icon: 'jar',
    description: 'Bring your own Java connector — upload JAR and define entry class. Full SailPoint IIQ-style extensibility.',
    authType: 'custom',
    protocol: 'custom',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable', 'password_set', 'group_management'],
    provisioningDirection: ['push', 'pull', 'bidirectional'],
    configSchema: [
      { key: 'jar_path', label: 'JAR File Path', type: 'text', required: true, placeholder: '/app/external-jars/my-connector.jar' },
      { key: 'entry_class', label: 'Entry Class (fully qualified)', type: 'text', required: true, placeholder: 'com.mycompany.connector.MyConnector' },
      { key: 'config_json', label: 'Connector Config (JSON)', type: 'textarea', placeholder: '{"host":"...","apiKey":"..."}' },
    ],
    nativeSchema: [],
    dynamicSchema: true,
  },

  // ─── SAILPOINT MAINFRAME (connector-bundle-mainframe.jar) ──────────────────
  // These connectors are powered by the SailPoint connector-bundle-mainframe.jar
  // The JAR must be present in the connector runtime path for live provisioning.
  // Schema and config are based on the SMConnector implementation in the JAR.

  acf2: {
    displayName: 'ACF2 (Mainframe)',
    category: 'Mainframe',
    icon: 'mainframe',
    description: 'IBM ACF2 mainframe security — user and group management via RACF/ACF2 commands. Requires SailPoint connector-bundle-mainframe.jar.',
    authType: 'username_password',
    protocol: 'sailpoint_sm',
    jarRequired: 'connector-bundle-mainframe.jar',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable'],
    provisioningDirection: ['push', 'pull'],
    configSchema: [
      { key: 'host', label: 'Mainframe Host', type: 'text', required: true, placeholder: 'mainframe.example.com' },
      { key: 'port', label: 'Port', type: 'number', default: 3000 },
      { key: 'username', label: 'Service Account Username', type: 'text', required: true },
      { key: 'password', label: 'Service Account Password', type: 'password', required: true },
      { key: 'security_system', label: 'Security System', type: 'select', options: ['ACF2', 'RACF', 'TSS'], default: 'ACF2' },
      { key: 'ssl_enabled', label: 'SSL Enabled', type: 'boolean', default: true },
      { key: 'timeout', label: 'Connection Timeout (ms)', type: 'number', default: 30000 },
      { key: 'max_native_id_length', label: 'Max Native ID Length', type: 'number', default: 8 },
    ],
    nativeSchema: [
      { name: 'LOGONID', type: 'string', description: 'ACF2 Logon ID (user ID)', isUid: true },
      { name: 'NAME', type: 'string', description: 'Full Name' },
      { name: 'PASSWORD', type: 'secret', description: 'Password' },
      { name: 'SUSPEND', type: 'boolean', description: 'Account Suspended' },
      { name: 'DEPT', type: 'string', description: 'Department' },
      { name: 'DIV', type: 'string', description: 'Division' },
      { name: 'LID', type: 'string', description: 'LIDFIELD - User Attributes' },
      { name: 'RULEVIO', type: 'string', description: 'Rule Violation' },
      { name: 'GROUPS', type: 'multi_string', description: 'Group Memberships', readOnly: true },
      { name: 'PRFNAMES', type: 'multi_string', description: 'Profile Names', readOnly: true },
      { name: 'TSOCMD', type: 'string', description: 'TSO Command Class' },
      { name: 'RESTRICT', type: 'boolean', description: 'Restricted Logon' },
      { name: 'EXPDATE', type: 'string', description: 'Password Expiry Date' },
      { name: 'PSWD-DATE', type: 'string', description: 'Password Last Changed Date', readOnly: true },
    ],
  },

  racf: {
    displayName: 'RACF (Mainframe)',
    category: 'Mainframe',
    icon: 'mainframe',
    description: 'IBM RACF (Resource Access Control Facility) mainframe security. Requires SailPoint connector-bundle-mainframe.jar.',
    authType: 'username_password',
    protocol: 'sailpoint_sm',
    jarRequired: 'connector-bundle-mainframe.jar',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable'],
    provisioningDirection: ['push', 'pull'],
    configSchema: [
      { key: 'host', label: 'Mainframe Host', type: 'text', required: true, placeholder: 'mainframe.example.com' },
      { key: 'port', label: 'Port', type: 'number', default: 3000 },
      { key: 'username', label: 'Service Account Username', type: 'text', required: true },
      { key: 'password', label: 'Service Account Password', type: 'password', required: true },
      { key: 'security_system', label: 'Security System', type: 'select', options: ['ACF2', 'RACF', 'TSS'], default: 'RACF' },
      { key: 'ssl_enabled', label: 'SSL Enabled', type: 'boolean', default: true },
      { key: 'timeout', label: 'Connection Timeout (ms)', type: 'number', default: 30000 },
    ],
    nativeSchema: [
      { name: 'USERID', type: 'string', description: 'RACF User ID', isUid: true },
      { name: 'NAME', type: 'string', description: 'Full Name' },
      { name: 'OWNER', type: 'string', description: 'Profile Owner' },
      { name: 'DFLTGRP', type: 'string', description: 'Default Group' },
      { name: 'PASSDATE', type: 'string', description: 'Last Password Change Date', readOnly: true },
      { name: 'PWDINTERVAL', type: 'number', description: 'Password Expiry Interval (days)' },
      { name: 'REVOKE', type: 'boolean', description: 'Account Revoked' },
      { name: 'UACC', type: 'string', description: 'Universal Access' },
      { name: 'CONNECT', type: 'multi_string', description: 'Group Connections', readOnly: true },
      { name: 'CLAUTH', type: 'multi_string', description: 'Class Authorizations' },
      { name: 'SPECIAL', type: 'boolean', description: 'RACF Special Attribute' },
      { name: 'OPERATIONS', type: 'boolean', description: 'RACF Operations Attribute' },
      { name: 'AUDITOR', type: 'boolean', description: 'RACF Auditor Attribute' },
    ],
  },

  top_secret: {
    displayName: 'Top Secret (Mainframe)',
    category: 'Mainframe',
    icon: 'mainframe',
    description: 'Broadcom Top Secret mainframe security manager. Requires SailPoint connector-bundle-mainframe.jar.',
    authType: 'username_password',
    protocol: 'sailpoint_sm',
    jarRequired: 'connector-bundle-mainframe.jar',
    capabilities: ['read', 'create', 'update', 'delete', 'enable', 'disable'],
    provisioningDirection: ['push', 'pull'],
    configSchema: [
      { key: 'host', label: 'Mainframe Host', type: 'text', required: true, placeholder: 'mainframe.example.com' },
      { key: 'port', label: 'Port', type: 'number', default: 3000 },
      { key: 'username', label: 'Service Account Username', type: 'text', required: true },
      { key: 'password', label: 'Service Account Password', type: 'password', required: true },
      { key: 'security_system', label: 'Security System', type: 'select', options: ['ACF2', 'RACF', 'TSS'], default: 'TSS' },
      { key: 'ssl_enabled', label: 'SSL Enabled', type: 'boolean', default: true },
      { key: 'timeout', label: 'Connection Timeout (ms)', type: 'number', default: 30000 },
    ],
    nativeSchema: [
      { name: 'ACID', type: 'string', description: 'Top Secret ACID (Account ID)', isUid: true },
      { name: 'NAME', type: 'string', description: 'Full Name' },
      { name: 'DEPT', type: 'string', description: 'Department' },
      { name: 'DIV', type: 'string', description: 'Division' },
      { name: 'FACILITY', type: 'multi_string', description: 'Facility Access', readOnly: true },
      { name: 'SUSPEND', type: 'boolean', description: 'Account Suspended' },
      { name: 'EXPDATE', type: 'string', description: 'Expiry Date' },
      { name: 'PASSDATE', type: 'string', description: 'Last Password Change', readOnly: true },
      { name: 'GROUPS', type: 'multi_string', description: 'Group Memberships', readOnly: true },
      { name: 'PROF', type: 'multi_string', description: 'Profiles', readOnly: true },
    ],
  },

  // ─── SAILPOINT IIQ CONNECTOR (connector-bundle-identityiq.jar) ─────────────
  // Uses the SailPoint OpenConnector SDK. The JAR provides the base framework.
  // IIQ connector aggregates identities from another SailPoint IdentityIQ instance.

  sailpoint_iiq: {
    displayName: 'SailPoint IdentityIQ',
    category: 'IAM Platform',
    icon: 'sailpoint',
    description: 'Aggregate identities and roles from a SailPoint IdentityIQ instance via REST API. Useful for IIQ-to-NexusIAM migration or hybrid scenarios.',
    authType: 'basic_auth',
    protocol: 'sailpoint_rest',
    jarRequired: 'connector-bundle-identityiq.jar',
    capabilities: ['read', 'create', 'update', 'disable'],
    provisioningDirection: ['pull', 'push'],
    configSchema: [
      { key: 'iiq_url', label: 'IIQ Base URL', type: 'text', required: true, placeholder: 'https://iiq.example.com/identityiq' },
      { key: 'username', label: 'IIQ Admin Username', type: 'text', required: true, placeholder: 'spadmin' },
      { key: 'password', label: 'IIQ Admin Password', type: 'password', required: true },
      { key: 'page_size', label: 'Page Size', type: 'number', default: 100 },
      { key: 'ssl_verify', label: 'Verify SSL Certificate', type: 'boolean', default: true },
      { key: 'application_name', label: 'Source Application Name (optional)', type: 'text', placeholder: 'Leave blank to aggregate all identities' },
    ],
    nativeSchema: [
      { name: 'name', type: 'string', description: 'IIQ Identity Name', isUid: true },
      { name: 'displayName', type: 'string', description: 'Display Name' },
      { name: 'email', type: 'string', description: 'Email Address' },
      { name: 'firstname', type: 'string', description: 'First Name' },
      { name: 'lastname', type: 'string', description: 'Last Name' },
      { name: 'department', type: 'string', description: 'Department' },
      { name: 'title', type: 'string', description: 'Job Title' },
      { name: 'manager', type: 'string', description: 'Manager Identity Name' },
      { name: 'inactive', type: 'boolean', description: 'Account Inactive' },
      { name: 'bundles', type: 'multi_string', description: 'Assigned Roles (Bundles)', readOnly: true },
      { name: 'links', type: 'multi_string', description: 'Application Accounts (Links)', readOnly: true },
      { name: 'assignedRoles', type: 'multi_string', description: 'Assigned Business Roles', readOnly: true },
      { name: 'detectedRoles', type: 'multi_string', description: 'Detected Roles', readOnly: true },
    ],
  },
};

// Connector categories for grouping in UI
const CATEGORIES = [
  'Directory',
  'Cloud IAM',
  'HR Systems',
  'Database',
  'Standard Protocol',
  'Enterprise SaaS',
  'ITSM',
  'Developer Tools',
  'Productivity',
  'Collaboration',
  'Cloud Platform',
  'Cloud Storage',
  'CRM',
  'Customer Support',
  'Privileged Access',
  'File-based',
  'Mainframe',
  'IAM Platform',
  'Custom',
];

module.exports = { CONNECTORS, CATEGORIES };
