name: NexusIAM CI

on:
push:
branches:
- master
pull_request:
branches:
- master

jobs:
build-backend:
runs-on: ubuntu-latest

defaults:
  run:
    working-directory: backend

steps:
  - uses: actions/checkout@v4

  - name: Verify Backend Path
    run: |
      pwd
      ls -la
      ls -la ../
      ls -la

  - uses: actions/setup-node@v4
    with:
      node-version: 22

  - run: npm install

build-frontend:
runs-on: ubuntu-latest

defaults:
  run:
    working-directory: frontend

steps:
  - uses: actions/checkout@v4

  - name: Verify Frontend Path
    run: |
      pwd
      ls -la
      ls -la ../
      ls -la

  - uses: actions/setup-node@v4
    with:
      node-version: 22

  - run: npm install